version: '3.4'

services:
  postgres:
    container_name: postgres
    image: postgres:15.0
    restart: unless-stopped
    env_file: .env
    ports:
      - 5432:5432 

  drilling-api:
    container_name: drilling-api
    build:
      context: .
      dockerfile: Drilling/Dockerfile
    image: drilling-image
    env_file: .env
    restart: unless-stopped
    ports:
      - 85:80
      - 86:443
     